# Generated by Django 6.0.5 on 2026-08-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('customers', 'customers'), ('debts', 'debts'), ('payments', 'payments'), ('products', 'products')], max_length=20)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted'), ('paid', 'paid'), ('low_stock', 'low_stock'), ('out_of_stock', 'out_of_stock')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
