# Generated by Django 6.0.5 on 2026-07-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_alter_customershop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
