# Generated by Django 6.0.5 on 2026-07-11 08:11

import debts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_remove_debt_paid_amount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_id',
            field=models.CharField(default=debts.models.generate_debt_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=debts.models.generate_payment_id, editable=False, max_length=20, unique=True),
        ),
    ]
